import type { Project, Task, ThreadItem } from './types';

const item = (data: Omit<ThreadItem, 'version'>): ThreadItem => ({ version: 1, ...data });

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

export const fixtureProjects: Project[] = [
  {
    id: 'PRJ-CLEW',
    name: 'Clew',
    localPath: '/tmp/clew',
    repositoryRoot: '/tmp/clew',
    defaultBranch: 'main',
    createdAt: '2026-08-28T09:00:00.000Z',
    updatedAt: '2026-08-28T10:04:00.000Z',
  },
  {
    id: 'PRJ-LYKAR',
    name: 'Lykar',
    localPath: '/tmp/lykar',
    repositoryRoot: '/tmp/lykar',
    defaultBranch: 'main',
    createdAt: '2026-08-28T09:00:00.000Z',
    updatedAt: '2026-08-28T09:30:00.000Z',
  },
];

const standardThread: ThreadItem[] = [
  item({
    id: 'thread-1',
    cursor: 1,
    kind: 'task_created',
    at: '2026-08-28T09:42:00.000Z',
    source: { kind: 'event', id: 'event-1', eventType: 'TASK_CREATED' },
    summary: 'Task created: Replace auth middleware',
    taskId: 'CLEW-071',
  }),
  item({
    id: 'thread-2',
    cursor: 2,
    kind: 'run_started',
    at: '2026-08-28T09:43:11.000Z',
    source: { kind: 'run', id: 'run-1', eventType: 'STAGE_RUN_STARTED' },
    summary: 'Stage worker run started (attempt 1)',
    taskId: 'CLEW-071',
    stageId: 'worker',
    runId: 'run-1',
  }),
  item({
    id: 'thread-3',
    cursor: 3,
    kind: 'review_findings',
    at: '2026-08-28T09:51:00.000Z',
    source: { kind: 'review', id: 'event-3', eventType: 'CHANGES_REQUESTED' },
    summary: '1 review finding requires correction',
    taskId: 'CLEW-071',
    stageId: 'worker',
    runId: 'run-1',
  }),
  item({
    id: 'thread-4',
    cursor: 4,
    kind: 'retry_scheduled',
    at: '2026-08-28T09:51:03.000Z',
    source: { kind: 'event', id: 'event-4', eventType: 'RETRY_SCHEDULED' },
    summary: 'Retry scheduled (attempt 2)',
    taskId: 'CLEW-071',
    stageId: 'worker',
  }),
  item({
    id: 'thread-5',
    cursor: 5,
    kind: 'run_started',
    at: '2026-08-28T09:52:10.000Z',
    source: { kind: 'run', id: 'run-2', eventType: 'STAGE_RUN_STARTED' },
    summary: 'Stage worker run started (attempt 2)',
    taskId: 'CLEW-071',
    stageId: 'worker',
    runId: 'run-2',
  }),
  item({
    id: 'thread-6',
    cursor: 6,
    kind: 'review_recorded',
    at: '2026-08-28T10:04:00.000Z',
    source: { kind: 'review', id: 'event-6', eventType: 'REVIEW_RECORDED' },
    summary: 'Review recorded: pass',
    taskId: 'CLEW-071',
    stageId: 'worker',
    runId: 'run-2',
  }),
  item({
    id: 'thread-7',
    cursor: 7,
    kind: 'task_ready',
    at: '2026-08-28T10:04:02.000Z',
    source: { kind: 'event', id: 'event-7', eventType: 'TASK_STATE_CHANGED' },
    summary: 'Task state changed to READY',
    taskId: 'CLEW-071',
  }),
];

export const fixtureTasks: Task[] = [
  {
    id: 'CLEW-071',
    projectId: 'PRJ-CLEW',
    createdAt: '2026-08-28T09:40:00.000Z',
    title: 'Replace auth middleware',
    goal: 'Move the local auth boundary behind a typed adapter.',
    profile: 'standard',
    tags: ['backend', 'auth'],
    state: 'READY',
    attention: null,
    revision: 'a91c4e2',
    finalization: {
      version: 1,
      taskId: 'CLEW-071',
      runId: 'run-2',
      state: 'READY',
      ready: true,
      checks: [
        {
          id: 'verification',
          label: 'Verification passed',
          passed: true,
          blocking: true,
          detail: '1 check',
        },
      ],
      blockingReasons: [],
      availableActions: ['review_changes', 'complete'],
      recommendedAction: 'complete',
      git: {
        enabled: false,
        targetBranch: 'main',
        strategy: 'squash',
        cleanup: true,
        dirty: false,
        conflicts: null,
      },
    },
    attempts: 2,
    roles: ['worker', 'reviewer'],
    runs: [
      {
        id: 'run-1',
        stageId: 'worker',
        attempt: 1,
        status: 'COMPLETED',
        harness: 'codex',
        sessionId: 'thread-1',
        workspace: '/tmp/clew-workspace',
        commitSha: 'a91c4e2',
        startedAt: '2026-08-28T09:43:00.000Z',
        finishedAt: '2026-08-28T09:51:00.000Z',
      },
      {
        id: 'run-2',
        stageId: 'worker',
        attempt: 2,
        status: 'COMPLETED',
        harness: 'codex',
        sessionId: 'thread-2',
        workspace: '/tmp/clew-workspace',
        commitSha: 'a91c4e2',
        startedAt: '2026-08-28T09:52:00.000Z',
        finishedAt: '2026-08-28T10:04:00.000Z',
      },
    ],
    stages: [{ id: 'worker', status: 'COMPLETED', kind: 'worker' }],
    reviewed: true,
    findings: 0,
    thread: {
      version: 1,
      items: standardThread,
      nextCursor: null,
      hasMore: false,
      redaction: 'public-safe',
    },
    events: standardThread.map((entry) => ({
      seq: entry.cursor,
      type: entry.source.eventType ?? entry.kind,
      at: entry.at,
      payload: {},
    })),
    agentSessions: [
      {
        id: 'CLEW-071:architect:arch-session-1',
        taskId: 'CLEW-071',
        role: 'architect',
        harness: 'codex',
        sessionId: 'arch-session-1',
        workspace: '/tmp/clew-workspace',
        terminalAccess: 'controller_local',
        createdAt: '2026-08-28T09:40:00.000Z',
      },
    ],
  },
  {
    id: 'ACC-DEEP',
    projectId: 'PRJ-CLEW',
    createdAt: '2026-08-28T09:55:00.000Z',
    title: 'Parallel cache migration',
    goal: 'Split backend and frontend work, then integrate safely.',
    profile: 'deep',
    tags: ['infrastructure', 'cache'],
    state: 'WAITING_FOR_HUMAN',
    attention: 'PLAN_APPROVAL_REQUIRED',
    revision: null,
    attempts: 0,
    roles: ['architect', 'worker', 'reviewer'],
    runs: [],
    stages: [
      { id: 'backend', status: 'QUEUED', kind: 'worker' },
      { id: 'frontend', status: 'QUEUED', kind: 'worker' },
      { id: 'integration', status: 'BLOCKED', kind: 'integration' },
    ],
    reviewed: false,
    findings: 0,
    thread: {
      version: 1,
      items: [
        item({
          id: 'deep-1',
          cursor: 1,
          kind: 'plan_approval_required',
          at: '2026-08-28T10:00:00.000Z',
          source: { kind: 'event', id: 'event-41', eventType: 'PLAN_APPROVAL_REQUIRED' },
          summary: 'Plan approval is required',
          taskId: 'ACC-DEEP',
        }),
      ],
      nextCursor: null,
      hasMore: false,
      redaction: 'public-safe',
    },
    events: [],
    agentSessions: [
      {
        id: 'ACC-DEEP:architect:arch-session-deep',
        taskId: 'ACC-DEEP',
        role: 'architect',
        harness: 'codex',
        sessionId: 'arch-session-deep',
        workspace: '/tmp/clew-workspace-deep',
        terminalAccess: 'controller_local',
        createdAt: '2026-08-28T09:55:00.000Z',
      },
    ],
  },
  {
    id: 'CLW-EXEC',
    projectId: 'PRJ-CLEW',
    createdAt: '2026-08-28T09:50:00.000Z',
    title: 'Session revocation rollout',
    goal: 'Roll out session revocation behind the new auth boundary.',
    profile: 'standard',
    tags: ['auth'],
    state: 'EXECUTING',
    attention: null,
    revision: null,
    attempts: 1,
    roles: ['worker', 'reviewer'],
    runs: [
      {
        id: 'run-exec',
        stageId: 'worker',
        attempt: 1,
        status: 'RUNNING',
        harness: 'opencode',
        sessionId: 'sess-exec',
        workspace: '/tmp/clew-workspace',
        commitSha: null,
        startedAt: minutesAgo(12),
        finishedAt: null,
      },
    ],
    stages: [{ id: 'worker', status: 'RUNNING', kind: 'worker' }],
    reviewed: false,
    findings: 0,
    thread: {
      version: 1,
      items: [],
      nextCursor: null,
      hasMore: false,
      redaction: 'public-safe',
    },
    events: [],
    agentSessions: [],
  },
  {
    id: 'CLW-DONE',
    projectId: 'PRJ-CLEW',
    createdAt: '2026-08-28T09:00:00.000Z',
    title: 'Refresh token cleanup',
    goal: 'Remove expired refresh tokens from storage.',
    profile: 'quick',
    tags: [],
    state: 'COMPLETED',
    attention: null,
    revision: 'c3f0a11',
    attempts: 1,
    roles: ['worker'],
    runs: [
      {
        id: 'run-done',
        stageId: 'worker',
        attempt: 1,
        status: 'COMPLETED',
        harness: 'codex',
        sessionId: 'sess-done',
        workspace: '/tmp/clew-workspace',
        commitSha: 'c3f0a11',
        startedAt: minutesAgo(90),
        finishedAt: minutesAgo(60),
      },
    ],
    stages: [{ id: 'worker', status: 'COMPLETED', kind: 'worker' }],
    reviewed: true,
    findings: 0,
    thread: {
      version: 1,
      items: [],
      nextCursor: null,
      hasMore: false,
      redaction: 'public-safe',
    },
    events: [],
    agentSessions: [],
    completion: { at: minutesAgo(58), actor: 'test' },
  },
  {
    id: 'CLW-FAIL',
    projectId: 'PRJ-CLEW',
    createdAt: '2026-08-28T09:20:00.000Z',
    title: 'Cache invalidation probe',
    goal: 'Probe cache invalidation paths.',
    profile: 'quick',
    tags: [],
    state: 'FAILED',
    attention: null,
    revision: null,
    attempts: 1,
    roles: ['worker'],
    runs: [
      {
        id: 'run-fail',
        stageId: 'worker',
        attempt: 1,
        status: 'FAILED',
        harness: 'codex',
        sessionId: 'sess-fail',
        workspace: '/tmp/clew-workspace',
        commitSha: null,
        startedAt: minutesAgo(30),
        finishedAt: minutesAgo(28),
      },
    ],
    stages: [{ id: 'worker', status: 'FAILED', kind: 'worker' }],
    reviewed: false,
    findings: 1,
    thread: {
      version: 1,
      items: [],
      nextCursor: null,
      hasMore: false,
      redaction: 'public-safe',
    },
    events: [],
    agentSessions: [],
  },
];
