import type { Task, ThreadItem } from './types';

const item = (data: Omit<ThreadItem, 'version'>): ThreadItem => ({ version: 1, ...data });

const standardThread: ThreadItem[] = [
  item({
    id: 'thread-1',
    cursor: 1,
    kind: 'task_created',
    at: '2026-08-28T09:42:00.000Z',
    source: { kind: 'event', id: 'event-1', eventType: 'TASK_CREATED' },
    summary: 'Task created: Replace auth middleware',
    taskId: 'CLEW-071',
  }),
  item({
    id: 'thread-2',
    cursor: 2,
    kind: 'run_started',
    at: '2026-08-28T09:43:11.000Z',
    source: { kind: 'run', id: 'run-1', eventType: 'STAGE_RUN_STARTED' },
    summary: 'Stage worker run started (attempt 1)',
    taskId: 'CLEW-071',
    stageId: 'worker',
    runId: 'run-1',
  }),
  item({
    id: 'thread-3',
    cursor: 3,
    kind: 'review_findings',
    at: '2026-08-28T09:51:00.000Z',
    source: { kind: 'review', id: 'event-3', eventType: 'CHANGES_REQUESTED' },
    summary: '1 review finding requires correction',
    taskId: 'CLEW-071',
    stageId: 'worker',
    runId: 'run-1',
  }),
  item({
    id: 'thread-4',
    cursor: 4,
    kind: 'retry_scheduled',
    at: '2026-08-28T09:51:03.000Z',
    source: { kind: 'event', id: 'event-4', eventType: 'RETRY_SCHEDULED' },
    summary: 'Retry scheduled (attempt 2)',
    taskId: 'CLEW-071',
    stageId: 'worker',
  }),
  item({
    id: 'thread-5',
    cursor: 5,
    kind: 'run_started',
    at: '2026-08-28T09:52:10.000Z',
    source: { kind: 'run', id: 'run-2', eventType: 'STAGE_RUN_STARTED' },
    summary: 'Stage worker run started (attempt 2)',
    taskId: 'CLEW-071',
    stageId: 'worker',
    runId: 'run-2',
  }),
  item({
    id: 'thread-6',
    cursor: 6,
    kind: 'review_recorded',
    at: '2026-08-28T10:04:00.000Z',
    source: { kind: 'review', id: 'event-6', eventType: 'REVIEW_RECORDED' },
    summary: 'Review recorded: pass',
    taskId: 'CLEW-071',
    stageId: 'worker',
    runId: 'run-2',
  }),
  item({
    id: 'thread-7',
    cursor: 7,
    kind: 'task_ready',
    at: '2026-08-28T10:04:02.000Z',
    source: { kind: 'event', id: 'event-7', eventType: 'TASK_STATE_CHANGED' },
    summary: 'Task state changed to READY',
    taskId: 'CLEW-071',
  }),
];

export const fixtureTasks: Task[] = [
  {
    id: 'CLEW-071',
    title: 'Replace auth middleware',
    goal: 'Move the local auth boundary behind a typed adapter.',
    profile: 'standard',
    state: 'READY',
    attention: null,
    revision: 'a91c4e2',
    attempts: 2,
    stages: [{ id: 'worker', status: 'COMPLETED', kind: 'worker' }],
    reviewed: true,
    findings: 0,
    thread: {
      version: 1,
      items: standardThread,
      nextCursor: null,
      hasMore: false,
      redaction: 'public-safe',
    },
    events: standardThread.map((entry) => ({
      seq: entry.cursor,
      type: entry.source.eventType ?? entry.kind,
      at: entry.at,
      payload: {},
    })),
  },
  {
    id: 'ACC-DEEP',
    title: 'Parallel cache migration',
    goal: 'Split backend and frontend work, then integrate safely.',
    profile: 'deep',
    state: 'WAITING_FOR_HUMAN',
    attention: 'PLAN_APPROVAL_REQUIRED',
    revision: null,
    attempts: 0,
    stages: [
      { id: 'backend', status: 'QUEUED', kind: 'worker' },
      { id: 'frontend', status: 'QUEUED', kind: 'worker' },
      { id: 'integration', status: 'BLOCKED', kind: 'integration' },
    ],
    reviewed: false,
    findings: 0,
    thread: {
      version: 1,
      items: [
        item({
          id: 'deep-1',
          cursor: 1,
          kind: 'plan_approval_required',
          at: '2026-08-28T10:00:00.000Z',
          source: { kind: 'event', id: 'event-41', eventType: 'PLAN_APPROVAL_REQUIRED' },
          summary: 'Plan approval is required',
          taskId: 'ACC-DEEP',
        }),
      ],
      nextCursor: null,
      hasMore: false,
      redaction: 'public-safe',
    },
    events: [],
  },
];
